/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;

/**
 *
 * @author vanel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_suppliers = new javax.swing.JButton();
        bt_sales = new javax.swing.JButton();
        bt_products = new javax.swing.JButton();
        bt_stock = new javax.swing.JButton();
        bt_others = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("EasyPub Dashboard");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 490, 58);

        bt_suppliers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_suppliers.setText("Suppliers");
        bt_suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suppliersActionPerformed(evt);
            }
        });
        getContentPane().add(bt_suppliers);
        bt_suppliers.setBounds(650, 150, 200, 130);

        bt_sales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_sales.setText("Sales");
        bt_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salesActionPerformed(evt);
            }
        });
        getContentPane().add(bt_sales);
        bt_sales.setBounds(110, 150, 200, 130);

        bt_products.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_products.setText("Products");
        bt_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_productsActionPerformed(evt);
            }
        });
        getContentPane().add(bt_products);
        bt_products.setBounds(380, 150, 200, 130);

        bt_stock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_stock.setText("Stock");
        bt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stockActionPerformed(evt);
            }
        });
        getContentPane().add(bt_stock);
        bt_stock.setBounds(250, 350, 200, 130);

        bt_others.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_others.setText("Others");
        bt_others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_othersActionPerformed(evt);
            }
        });
        getContentPane().add(bt_others);
        bt_others.setBounds(530, 350, 200, 130);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suppliersActionPerformed
        Suppliers a = new Suppliers();
        a.setVisible(true);
    }//GEN-LAST:event_bt_suppliersActionPerformed

    private void bt_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salesActionPerformed
       Sale b = new Sale();
        b.setVisible(true);
    }//GEN-LAST:event_bt_salesActionPerformed

    private void bt_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_productsActionPerformed
        Products c = new Products();
        c.setVisible(true);
    }//GEN-LAST:event_bt_productsActionPerformed

    private void bt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stockActionPerformed
        Stock d = new Stock();
        d.setVisible(true);
    }//GEN-LAST:event_bt_stockActionPerformed

    private void bt_othersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_othersActionPerformed
        Others e = new Others();
        e.setVisible(true);
    }//GEN-LAST:event_bt_othersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_others;
    private javax.swing.JButton bt_products;
    private javax.swing.JButton bt_sales;
    private javax.swing.JButton bt_stock;
    private javax.swing.JButton bt_suppliers;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
