/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;

import java.awt.Toolkit;

/**
 *
 * @author vanel
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setExtendedState(Main.MAXIMIZED_BOTH);
    }
    
   /* this.setAlwaysOnTop(true);
    Toolkit tk = Toolkit.getDefaultToolkit();
    int vert = (int)tk.getScreenSize().getWidth();
    int horz = (int)tk.getScreenSize().getHeight();
    insets maxScr = Toolkit.getDefaultToolkit().getScreeninsets(getGraphicsConfiguration());
    int screenSize = maxScr.bottom;
    
    this.setSize(vert, horz);*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_suppliers = new javax.swing.JButton();
        bt_others = new javax.swing.JButton();
        bt_products = new javax.swing.JButton();
        bt_stock = new javax.swing.JButton();
        bt_sales = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("EasyPub Dashboard");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_suppliers.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_suppliers.setText("Suppliers");
        bt_suppliers.setPreferredSize(new java.awt.Dimension(200, 120));
        bt_suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_suppliersActionPerformed(evt);
            }
        });
        jPanel1.add(bt_suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        bt_others.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_others.setText("Others");
        bt_others.setPreferredSize(new java.awt.Dimension(200, 120));
        bt_others.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_othersActionPerformed(evt);
            }
        });
        jPanel1.add(bt_others, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        bt_products.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_products.setText("Products");
        bt_products.setPreferredSize(new java.awt.Dimension(200, 120));
        bt_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_productsActionPerformed(evt);
            }
        });
        jPanel1.add(bt_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        bt_stock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_stock.setText("Stock");
        bt_stock.setPreferredSize(new java.awt.Dimension(200, 120));
        bt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stockActionPerformed(evt);
            }
        });
        jPanel1.add(bt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 220, -1, -1));

        bt_sales.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt_sales.setText("Sales");
        bt_sales.setPreferredSize(new java.awt.Dimension(200, 120));
        bt_sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salesActionPerformed(evt);
            }
        });
        jPanel1.add(bt_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 220, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_suppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_suppliersActionPerformed
        Suppliers a = new Suppliers();
        a.setVisible(true);
    }//GEN-LAST:event_bt_suppliersActionPerformed

    private void bt_salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salesActionPerformed
       Sale b = new Sale();
        b.setVisible(true);
    }//GEN-LAST:event_bt_salesActionPerformed

    private void bt_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_productsActionPerformed
        Products c = new Products();
        c.setVisible(true);
    }//GEN-LAST:event_bt_productsActionPerformed

    private void bt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stockActionPerformed
        Stock d = new Stock();
        d.setVisible(true);
    }//GEN-LAST:event_bt_stockActionPerformed

    private void bt_othersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_othersActionPerformed
        Others e = new Others();
        e.setVisible(true);
    }//GEN-LAST:event_bt_othersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_others;
    private javax.swing.JButton bt_products;
    private javax.swing.JButton bt_sales;
    private javax.swing.JButton bt_stock;
    private javax.swing.JButton bt_suppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
