/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vanel
 */
public class Others extends javax.swing.JFrame {

    /**
     * Creates new form Others
     */
    public Others() {
        initComponents();
    }
    
    Connection cnct;
    PreparedStatement prepst;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txusername = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txpassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txcategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txlname = new javax.swing.JTextField();
        txemail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Categories");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 290, 260, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Users");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 20, 130, 50);

        filler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(filler1);
        filler1.setBounds(215, 96, 0, 100);

        jButton3.setText("Generate");
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 230, 77, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(520, 130, 380, 20);

        jLabel4.setText("Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 110, 24, 14);

        jLabel5.setText("Dates");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 170, 40, 14);

        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(470, 20, 10, 560);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 110, 40, 14);
        getContentPane().add(txusername);
        txusername.setBounds(60, 130, 350, 20);

        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 210, 24, 14);
        getContentPane().add(txpassword);
        txpassword.setBounds(60, 280, 110, 20);

        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 260, 46, 14);

        jLabel8.setText("Confirm password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 310, 110, 14);

        jButton4.setText("Create");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(60, 370, 65, 23);

        textField1.setText("textField1");
        getContentPane().add(textField1);
        textField1.setBounds(520, 190, 60, 20);

        jPasswordField2.setText("jPasswordField2");
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(60, 330, 112, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setText("Reports");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(630, 20, 190, 60);

        jLabel10.setText("New category");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(520, 420, 80, 14);
        getContentPane().add(txcategory);
        txcategory.setBounds(520, 440, 110, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Category_ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 380, 230, 140);

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        getContentPane().add(btAdd);
        btAdd.setBounds(520, 550, 70, 23);

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        getContentPane().add(btEdit);
        btEdit.setBounds(600, 550, 73, 23);

        btDel.setText("Delete");
        getContentPane().add(btDel);
        btDel.setBounds(680, 550, 70, 23);

        jLabel11.setText("Last name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 160, 60, 14);
        getContentPane().add(txlname);
        txlname.setBounds(60, 180, 350, 20);
        getContentPane().add(txemail);
        txemail.setBounds(60, 230, 350, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String uName = txusername.getText();
        String lName = txlname.getText();
        String email = txemail.getText();
        String uPassword = txpassword.getText();
        
        if (uName.isEmpty()||lName.isEmpty()||email.isEmpty()||uPassword.isEmpty()){
            JOptionPane.showMessageDialog(this, "All fields from the form must be filled","Error",JOptionPane.ERROR_MESSAGE); 
            
            registerUser(uName,lName,email,uPassword);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cnct= DriverManager.getConnection("jdbc:mysql://localhost:3308/easypubdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            prepst = cnct.prepareStatement("insert into category (category)values(?)");
            prepst.setString(1,txcategory.getText());
            prepst.executeUpdate();
            JOptionPane.showMessageDialog(null, "New category registered"); 
            
            txcategory.setText("");
            txcategory.requestFocus();
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Others.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Others.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Others.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Others().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txcategory;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txlname;
    private javax.swing.JTextField txpassword;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables

    private void registerUser(String uName, String lName, String email, String uPassword) {
        Connection conDb = DtbConnect.connectDtb();
        if(conDb != null){
        try {            
            PreparedStatement pst = (PreparedStatement)
                    conDb.prepareStatement("INSERT INTO login (name, lastname, email, password) VALUES (?,?,?,?)");
            
            pst.setString(1, uName);
            pst.setString(2, lName);
            pst.setString(3, email);
            pst.setString(4, uPassword);
            int rss=pst.executeUpdate();
           
                JOptionPane.showMessageDialog(this, "New user registered","Sucess",JOptionPane.ERROR_MESSAGE);
            
            txusername.setText("");
            txlname.setText("");
            txemail.setText("");
            txpassword.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
                System.out.println("The connection is not available");
                }
    }
}
