/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vanel
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
    }
    
   /* public void drinkCost(){
        
        double sum = 0;
        
        for (int i = 0; i <jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        jTextField3.setText(Double.toString(sum));
       double dtotal = Double.parseDouble(jTextField3.getText());
       String stotal = String.format("£ %.2f", dtotal);
       jTextField3.setText(stotal);
        
    }

    public void change(){
        double sum = 0;
        double cash = Double.parseDouble(jTextField4.getText());
        
        for (int i = 0; i <jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        }
        double change = cash-sum;
        String custchange = String.format("£ %.2f", change);
        jTextField2.setText(custchange);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btX = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Coktails");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(67, 112, 46, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mixers");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 310, 38, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Shots");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 110, 35, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Whiskey");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 110, 52, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Rum");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(520, 210, 29, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gin");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 260, 19, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Vodka");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 160, 38, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(520, 130, 150, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(520, 180, 150, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(520, 280, 150, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(520, 230, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Liqueur");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 310, 45, 17);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(520, 330, 150, 20);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setText("Gin");
        jButton6.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton6.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton6.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 140, 74, 45);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Whiskey");
        jButton1.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton1.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton1.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 140, 77, 45);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Vodka");
        jButton3.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton3.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton3.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 191, 74, 45);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("Rum");
        jButton4.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton4.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton4.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton4);
        jButton4.setBounds(90, 191, 77, 45);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton7.setText("...");
        jButton7.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton7.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton7.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 242, 74, 45);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton8.setText("...");
        jButton8.setMaximumSize(new java.awt.Dimension(45, 45));
        jButton8.setMinimumSize(new java.awt.Dimension(45, 45));
        jButton8.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton8);
        jButton8.setBounds(90, 242, 77, 45);

        jButton9.setText("Coke");
        jButton9.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 340, 74, 45);

        jButton10.setText("Diet coke");
        jButton10.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(90, 340, 77, 45);

        jButton11.setText("Tonic");
        jButton11.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 390, 74, 45);

        jButton12.setText("Slim tonic");
        jButton12.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton12);
        jButton12.setBounds(90, 390, 77, 45);

        jButton13.setText("Premium tonic");
        jButton13.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(10, 440, 74, 45);

        jButton14.setText("Fanta orange");
        jButton14.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(90, 440, 76, 45);

        jButton15.setText("Fanta lemon");
        jButton15.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(10, 490, 74, 45);

        jButton16.setText("Lemonade");
        jButton16.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton16);
        jButton16.setBounds(90, 490, 76, 45);

        jButton17.setText("Ginger ale");
        jButton17.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(10, 540, 75, 45);

        jButton18.setText("Soda water");
        jButton18.setToolTipText("");
        jButton18.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton18);
        jButton18.setBounds(90, 540, 76, 45);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setText("Sales Dashboard");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 20, 402, 58);

        jButton19.setText("Sambuca");
        jButton19.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(180, 140, 74, 45);

        jButton20.setText("Baby guiness");
        jButton20.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton20);
        jButton20.setBounds(260, 140, 76, 45);

        jButton21.setText("Jagger");
        jButton21.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(180, 190, 75, 45);

        jButton22.setText("Tequila");
        jButton22.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton22);
        jButton22.setBounds(260, 190, 76, 45);

        jButton23.setText("...");
        jButton23.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton23);
        jButton23.setBounds(180, 240, 74, 45);

        jButton24.setText("...");
        jButton24.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton24);
        jButton24.setBounds(260, 240, 76, 45);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Spirits");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(240, 310, 36, 17);

        jButton25.setText("Coke");
        jButton25.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton25);
        jButton25.setBounds(180, 340, 74, 45);

        jButton26.setText("Diet coke");
        jButton26.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(260, 340, 77, 45);

        jButton27.setText("Tonic");
        jButton27.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton27);
        jButton27.setBounds(180, 390, 74, 45);

        jButton28.setText("Slim tonic");
        jButton28.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton28);
        jButton28.setBounds(260, 390, 77, 45);

        jButton29.setText("Premium tonic");
        jButton29.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(180, 440, 74, 45);

        jButton30.setText("Fanta orange");
        jButton30.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30);
        jButton30.setBounds(260, 440, 76, 45);

        jButton31.setText("Fanta lemon");
        jButton31.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton31);
        jButton31.setBounds(180, 490, 74, 45);

        jButton32.setText("Lemonade");
        jButton32.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton32);
        jButton32.setBounds(260, 490, 76, 45);

        jButton33.setText("Ginger ale");
        jButton33.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton33);
        jButton33.setBounds(180, 540, 75, 45);

        jButton34.setText("Soda water");
        jButton34.setToolTipText("");
        jButton34.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton34);
        jButton34.setBounds(260, 540, 76, 45);

        jButton35.setText("Coke");
        jButton35.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton35);
        jButton35.setBounds(350, 290, 74, 45);

        jButton36.setText("Diet coke");
        jButton36.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton36);
        jButton36.setBounds(430, 290, 77, 45);

        jButton37.setText("Tonic");
        jButton37.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton37);
        jButton37.setBounds(350, 340, 74, 45);

        jButton38.setText("Slim tonic");
        jButton38.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton38);
        jButton38.setBounds(430, 340, 77, 45);

        jButton39.setText("Premium tonic");
        jButton39.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(350, 390, 74, 45);

        jButton40.setText("Fanta orange");
        jButton40.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton40);
        jButton40.setBounds(430, 390, 76, 45);

        jButton41.setText("Fanta lemon");
        jButton41.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton41);
        jButton41.setBounds(350, 440, 74, 45);

        jButton42.setText("Lemonade");
        jButton42.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton42);
        jButton42.setBounds(430, 440, 76, 45);

        jButton43.setText("Ginger ale");
        jButton43.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(350, 490, 75, 45);

        jButton44.setText("Soda water");
        jButton44.setToolTipText("");
        jButton44.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton44);
        jButton44.setBounds(430, 490, 76, 45);

        jButton45.setText("Jagger");
        jButton45.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton45);
        jButton45.setBounds(350, 190, 75, 45);

        jButton46.setText("Tequila");
        jButton46.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton46);
        jButton46.setBounds(430, 190, 76, 45);

        jButton47.setText("...");
        jButton47.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton47);
        jButton47.setBounds(350, 240, 75, 45);

        jButton48.setText("...");
        jButton48.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton48);
        jButton48.setBounds(430, 240, 75, 45);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Beers");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 110, 33, 17);

        jButton49.setText("Sambuca");
        jButton49.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton49);
        jButton49.setBounds(350, 140, 74, 45);

        jButton50.setText("Baby guiness");
        jButton50.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton50);
        jButton50.setBounds(430, 140, 76, 45);

        jButton51.setText("Pay");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton51);
        jButton51.setBounds(780, 530, 160, 60);

        bt3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt3.setText("3");
        bt3.setAlignmentY(0.0F);
        bt3.setAutoscrolls(true);
        bt3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt3);
        bt3.setBounds(720, 530, 20, 20);

        bt1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt1.setText("1");
        bt1.setAlignmentY(0.0F);
        bt1.setAutoscrolls(true);
        bt1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt1);
        bt1.setBounds(680, 530, 20, 20);

        bt2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt2.setText("2");
        bt2.setAlignmentY(0.0F);
        bt2.setAutoscrolls(true);
        bt2.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt2);
        bt2.setBounds(700, 530, 20, 20);

        bt6.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt6.setText("6");
        bt6.setAlignmentY(0.0F);
        bt6.setAutoscrolls(true);
        bt6.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt6);
        bt6.setBounds(720, 550, 20, 20);

        bt4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt4.setText("4");
        bt4.setAlignmentY(0.0F);
        bt4.setAutoscrolls(true);
        bt4.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt4);
        bt4.setBounds(680, 550, 20, 20);

        bt5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt5.setText("5");
        bt5.setAlignmentY(0.0F);
        bt5.setAutoscrolls(true);
        bt5.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt5);
        bt5.setBounds(700, 550, 20, 20);

        bt0.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt0.setText("0");
        bt0.setAlignmentY(0.0F);
        bt0.setAutoscrolls(true);
        bt0.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt0);
        bt0.setBounds(740, 570, 40, 20);

        bt7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt7.setText("7");
        bt7.setAlignmentY(0.0F);
        bt7.setAutoscrolls(true);
        bt7.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt7);
        bt7.setBounds(680, 570, 20, 20);

        bt8.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt8.setText("8");
        bt8.setAlignmentY(0.0F);
        bt8.setAutoscrolls(true);
        bt8.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt8);
        bt8.setBounds(700, 570, 20, 20);

        btPrint.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btPrint.setText("Print");
        btPrint.setAlignmentY(0.0F);
        btPrint.setAutoscrolls(true);
        btPrint.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(btPrint);
        btPrint.setBounds(740, 530, 40, 20);

        jButton64.setText("Ginger ale");
        jButton64.setPreferredSize(new java.awt.Dimension(45, 45));
        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton64);
        jButton64.setBounds(350, 540, 75, 45);

        jButton65.setText("Soda water");
        jButton65.setToolTipText("");
        jButton65.setPreferredSize(new java.awt.Dimension(45, 45));
        getContentPane().add(jButton65);
        jButton65.setBounds(430, 540, 76, 45);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Wines");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(520, 360, 37, 17);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(520, 380, 150, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Change");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(720, 500, 50, 17);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(520, 430, 150, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Unit price", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 110, 260, 310);

        btX.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        btX.setText("X");
        btX.setAlignmentY(0.0F);
        btX.setAutoscrolls(true);
        btX.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(btX);
        btX.setBounds(740, 550, 40, 20);

        bt9.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        bt9.setText("9");
        bt9.setAlignmentY(0.0F);
        bt9.setAutoscrolls(true);
        bt9.setMargin(new java.awt.Insets(5, 5, 5, 5));
        getContentPane().add(bt9);
        bt9.setBounds(720, 570, 20, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cocktails");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 410, 60, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(780, 490, 160, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Total");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(740, 440, 40, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Cash");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(740, 470, 40, 17);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(780, 430, 160, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(780, 460, 160, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*double itemPrice = 1.00;
        
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        table.addRow(new Object[]{"Gin","1",itemPrice});
        drinkCost();*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
       
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
       
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
       
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        
    }//GEN-LAST:event_jButton51ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btX;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
