/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
/**
 *
 * @author vanel
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Stock() {
        initComponents();
        Connect();
        Product();
    }
    
    Connection cn;
    PreparedStatement pst;
    DefaultTableModel df;
    ResultSet rs;
  
    public void Connect(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn= DriverManager.getConnection("jdbc:mysql://localhost:3308/easypubdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        
    public void Product(){
        try {  
            pst = cn.prepareStatement("select product name");
            rs=pst.executeQuery();
            comboprod.removeAllItems();
            
            while(rs.next()){
                comboprod.addItem(rs.getString("product_name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    public void load() {
    int x;
        try {
            pst = cn.prepareStatement("select * from product");
        
    ResultSet rs = pst.executeQuery();
    ResultSetMetaData rd = rs.getMetaData();
    x = rd.getColumnCount();
    df = (DefaultTableModel)SupTable.getModel();    
    df.setRowCount(0);
    
    while(rs.next()){
        Vector vec = new Vector();
        for(int i=1; i<=x; i++){
            vec.add(rs.getString("product_name"));
            vec.add(rs.getString("transaction type"));
            vec.add(rs.getString("quantity"));
            
        }
        df.addRow(vec);
    }
    } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SupTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        jLabel3 = new javax.swing.JLabel();
        bt_save_sup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txqtystock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboprod = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        SupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product", "Quantity"
            }
        ));
        SupTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SupTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 530, 450);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 100, 117, 20);

        jLabel1.setText("Search");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 33, 14);
        getContentPane().add(filler1);
        filler1.setBounds(391, 0, 0, 303);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Stock");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 10, 130, 80);

        bt_save_sup.setText("Save");
        bt_save_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save_supActionPerformed(evt);
            }
        });
        getContentPane().add(bt_save_sup);
        bt_save_sup.setBounds(770, 560, 70, 23);

        jButton6.setText("Clear");
        jButton6.setActionCommand("Clear data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(847, 560, 70, 23);

        jLabel2.setText("Product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 130, 50, 14);

        jLabel4.setText("Transaction type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 180, 90, 14);
        getContentPane().add(txqtystock);
        txqtystock.setBounds(600, 250, 110, 20);

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 230, 60, 14);

        getContentPane().add(comboprod);
        comboprod.setBounds(600, 150, 300, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "goods receipt", "void", "waste" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(600, 200, 110, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_save_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save_supActionPerformed
        try {
            
            String product_name = comboprod.getSelectedItem().toString();            
            String transaction = jComboBox2.getSelectedItem().toString();
            String qty = txqtystock.getText();
            
            pst = cn.prepareStatement("insert new stock(supplier_name, transaction type, quantity)values(?,?,?)");
           
            pst.setString(1,product_name);
             pst.setString(2,transaction);
            pst.setString(3,qty);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Stock Added Successfully");
        
            comboprod.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
            txqtystock.setText("");
            comboprod.requestFocus();
            
            load();
            
        } catch (SQLException ex) {
            Logger.getLogger(Stock.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_save_supActionPerformed

    private void SupTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupTableMouseClicked
        df = (DefaultTableModel)SupTable.getModel();
        int selected = SupTable.getSelectedRow();
        int supplier_ID = Integer.parseInt(df.getValueAt(selected, 0).toString());
        
        comboprod.setSelectedItem(df.getValueAt(selected, 1).toString());
        jComboBox2.setSelectedItem(df.getValueAt(selected, 2).toString());
        txqtystock.setText(df.getValueAt(selected, 3).toString());
        
        bt_save_sup.setEnabled(false);
      
        
    }//GEN-LAST:event_SupTableMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        comboprod.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        txqtystock.setText("");
        comboprod.requestFocus();
            load();  
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SupTable;
    private javax.swing.JButton bt_save_sup;
    private javax.swing.JComboBox<String> comboprod;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txqtystock;
    // End of variables declaration//GEN-END:variables
}
