/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easypub;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
/**
 *
 * @author vanel
 */
public class Suppliers extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Suppliers() {
        initComponents();
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SupTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(32767, 200));
        jLabel3 = new javax.swing.JLabel();
        bt_save_sup = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txsupplier_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txadress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txeircode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txcontact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txcountry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 600));
        setMinimumSize(new java.awt.Dimension(950, 600));
        getContentPane().setLayout(null);

        SupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Supplier_ID", "Suppliers_name", "Adress", "Country", "Eircode", "Email", "Phone", "Contact"
            }
        ));
        SupTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SupTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 130, 530, 450);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(70, 100, 117, 20);

        jLabel1.setText("Search");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 33, 14);
        getContentPane().add(filler1);
        filler1.setBounds(391, 0, 0, 303);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Suppliers");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 10, 200, 80);

        bt_save_sup.setText("Save");
        bt_save_sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_save_supActionPerformed(evt);
            }
        });
        getContentPane().add(bt_save_sup);
        bt_save_sup.setBounds(630, 560, 70, 23);

        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(710, 560, 70, 23);

        jButton6.setText("Clear");
        jButton6.setActionCommand("Clear data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(860, 560, 57, 23);
        getContentPane().add(txsupplier_name);
        txsupplier_name.setBounds(600, 150, 300, 20);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 130, 27, 14);
        getContentPane().add(txadress);
        txadress.setBounds(600, 200, 300, 20);

        jLabel4.setText("Adress");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 180, 40, 14);
        getContentPane().add(txeircode);
        txeircode.setBounds(600, 250, 70, 20);

        jLabel5.setText("Eircode");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 230, 40, 14);
        getContentPane().add(txphone);
        txphone.setBounds(600, 350, 130, 20);

        jLabel7.setText("Phone");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 330, 60, 14);
        getContentPane().add(txcontact);
        txcontact.setBounds(760, 350, 140, 20);

        jLabel8.setText("Contact");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(760, 330, 60, 14);
        getContentPane().add(txemail);
        txemail.setBounds(600, 300, 220, 20);

        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(600, 280, 80, 14);
        getContentPane().add(txcountry);
        txcountry.setBounds(710, 250, 190, 20);

        jLabel10.setText("Country");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(710, 230, 40, 14);

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(790, 560, 63, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_save_supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_save_supActionPerformed
        
            /*String supplier_name = txsupplier_name.getText();
            String adress = txadress.getText();
            String country = txcountry.getText();
            String eircode = txeircode.getText();
            String email = txemail.getText();
            String phone = txphone.getText();
            String contact = txcontact.getText();*/
            
            
            
            
    }//GEN-LAST:event_bt_save_supActionPerformed

    private void SupTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupTableMouseClicked
        
        
    }//GEN-LAST:event_SupTableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
           
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SupTable;
    private javax.swing.JButton bt_save_sup;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txadress;
    private javax.swing.JTextField txcontact;
    private javax.swing.JTextField txcountry;
    private javax.swing.JTextField txeircode;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txphone;
    private javax.swing.JTextField txsupplier_name;
    // End of variables declaration//GEN-END:variables
}
